version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: sharebite
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:@db:5432/sharebite?sslmode=disable
    command: ["./main"]

    