version: '3.8'

services:
  postgres:
    image: postgres:latest
    container-name: sharebite-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres  # Use the service name as the host
      GIN_MODE: release # debug or release
      SEED_DB: false
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
