// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Dashboard() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section class=\"bg-white shadow rounded-lg p-6 mb-6\"><h2 class=\"text-xl font-semibold text-gray-900\">Welcome to Sharebite!</h2><p class=\"text-gray-700 mt-4\">At Sharebite, we are committed to providing an innovative platform that connects individuals, organizations, and local communities with food resources. Our mission is to reduce food waste while ensuring that food donations reach those in need. </p><p class=\"text-gray-700 mt-4\">We make it easy for people to donate food, request food donations, and contribute to a cause that matters. Whether you're a charity, a donor, or a recipient, Sharebite offers a seamless and transparent experience to help you make a positive impact on your community.</p></section><section class=\"bg-white shadow rounded-lg p-6\"><h2 class=\"text-xl font-semibold text-gray-900\">What We Do</h2><ul class=\"list-disc pl-5 mt-4 text-gray-700\"><li><strong>Food Donations:</strong> We connect individuals and organizations with surplus food to those in need.</li><li><strong>Donation Requests:</strong> Local charities can request specific types of donations directly through our platform.</li><li><strong>Impact Tracking:</strong> Our platform helps track donations and ensure transparency in the donation process.</li><li><strong>Community Engagement:</strong> We aim to foster a strong sense of community involvement through food security initiatives.</li></ul></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
