// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func DonationRequests() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!-- DonationRequests.templ --><div class=\"max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-lg space-y-6\"><h1 class=\"text-4xl font-extrabold text-center text-gray-800\">Donation Requests</h1><section class=\"space-y-4\"><h2 class=\"text-2xl font-semibold text-blue-600\">List of Donation Requests</h2><ul class=\"space-y-3\"><li class=\"flex justify-between p-4 bg-gray-100 rounded-lg shadow-sm\"><span class=\"text-lg text-gray-800\">Request 1</span> <span class=\"text-sm text-yellow-500 font-semibold\">Pending</span></li><li class=\"flex justify-between p-4 bg-green-100 rounded-lg shadow-sm\"><span class=\"text-lg text-gray-800\">Request 2</span> <span class=\"text-sm text-green-500 font-semibold\">Approved</span></li><li class=\"flex justify-between p-4 bg-blue-100 rounded-lg shadow-sm\"><span class=\"text-lg text-gray-800\">Request 3</span> <span class=\"text-sm text-blue-500 font-semibold\">Completed</span></li></ul></section></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
